# Generated by Django 4.0.2 on 2022-03-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='catagory',
            field=models.ManyToManyField(blank=True, null=True, to='blog_app.Catagory'),
        ),
    ]
