# Generated by Django 4.0.2 on 2022-03-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_rename_name_profile_username_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
    ]
